### ISSUE TITLE
Error failed in GameLoop.SaveLoaded Event

### ISSUE THREAD

**Issue by UfaiX04** [cdaragorn/Ui-Info-Suite#80]
`[UI Info Suite] This mod failed in the GameLoop.SaveLoaded event. Technical details:
FileNotFoundException: Could not load file or assembly 'System.Windows.Extensions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Impossibile trovare il file specificato.
File name: 'System.Windows.Extensions, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at UIInfoSuite.UIElements.ExperienceBar..ctor(IModHelper helper)
   at UIInfoSuite.Options.ModOptionsPageHandler..ctor(IModHelper helper, IDictionary`2 options) in C:\Users\Cdaragorn\Dropbox\dev\UiInfoSuite\Ui-Info-Suite\SDVModTest\Options\ModOptionsPageHandler.cs:line 52
   at UIInfoSuite.ModEntry.OnSaveLoaded(Object sender, SaveLoadedEventArgs e) in C:\Users\Cdaragorn\Dropbox\dev\UiInfoSuite\Ui-Info-Suite\SDVModTest\ModEntry.cs:line 118
   at StardewModdingAPI.Framework.Events.ManagedEvent`1.Raise(TEventArgs args, Func`2 match) `

Game works and runs but mod doesnt. Using this in 1.5.5

**Comment by nakorndev** [comment]
Same issue.

**Comment by UfaiX04** [comment]
> Same issue.

I fixed it, the issue is left open cause the project is abandoned, search for ui info suite 2 or join the stardew vallry modding discord
